transfer file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,23 +1,27 @@
 #!/usr/bin/env bash
 
-#check arguments passed to script
+# Script to transfer a file to a remote server using scp
 
-if [ $# -lt 4 ]
-then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Check number of arguments
+if [ $# -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
     exit 1
 fi
 
-path_to_file=$1
-ip=$2
-username=$3
-path_to_ssh_key=$4
+# Assign parameters to variables (without spaces around '=')
+path_to_file="$1"
+ip="$2"
+username="$3"
+path_to_ssh_key="$4"
+
+# Transfer file using scp with strict host key checking disabled
 scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-#check the exit status
-if [ $? -eq 0 ]
-then
-    echo "file transfered successfully"
+# Check the exit status of scp command
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully."
 else
-    echo "file not transfered"
+    echo "Error: File not transferred."
 fi
+
+exit 0
